/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BulkSearchResults from './BulkSearchResults';

/**
 * The BulkSearchResult model module.
 * @module model/BulkSearchResult
 * @version 1.0.0
 */
class BulkSearchResult {
    /**
     * Constructs a new <code>BulkSearchResult</code>.
     * @alias module:model/BulkSearchResult
     */
    constructor() { 
        
        BulkSearchResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkSearchResult} obj Optional instance to populate.
     * @return {module:model/BulkSearchResult} The populated <code>BulkSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkSearchResult();

            if (data.hasOwnProperty('data')) {
                obj['data'] = BulkSearchResults.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkSearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkSearchResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          BulkSearchResults.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/BulkSearchResults} data
 */
BulkSearchResult.prototype['data'] = undefined;






export default BulkSearchResult;

