/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BusinessAddress from './BusinessAddress';
import OrganisationIdentification from './OrganisationIdentification';

/**
 * The EntityDetails model module.
 * @module model/EntityDetails
 * @version 1.0.0
 */
class EntityDetails {
    /**
     * Constructs a new <code>EntityDetails</code>.
     * Details of the buyer or supplier from the search result.
     * @alias module:model/EntityDetails
     */
    constructor() { 
        
        EntityDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityDetails} obj Optional instance to populate.
     * @return {module:model/EntityDetails} The populated <code>EntityDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityDetails();

            if (data.hasOwnProperty('businessAddress')) {
                obj['businessAddress'] = BusinessAddress.constructFromObject(data['businessAddress']);
            }
            if (data.hasOwnProperty('businessName')) {
                obj['businessName'] = ApiClient.convertToType(data['businessName'], 'String');
            }
            if (data.hasOwnProperty('merchantIds')) {
                obj['merchantIds'] = ApiClient.convertToType(data['merchantIds'], ['String']);
            }
            if (data.hasOwnProperty('organisationIdentifications')) {
                obj['organisationIdentifications'] = ApiClient.convertToType(data['organisationIdentifications'], [OrganisationIdentification]);
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityDetails</code>.
     */
    static validateJSON(data) {
        // validate the optional field `businessAddress`
        if (data['businessAddress']) { // data not null
          BusinessAddress.validateJSON(data['businessAddress']);
        }
        // ensure the json data is a string
        if (data['businessName'] && !(typeof data['businessName'] === 'string' || data['businessName'] instanceof String)) {
            throw new Error("Expected the field `businessName` to be a primitive type in the JSON string but got " + data['businessName']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['merchantIds'])) {
            throw new Error("Expected the field `merchantIds` to be an array in the JSON data but got " + data['merchantIds']);
        }
        if (data['organisationIdentifications']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['organisationIdentifications'])) {
                throw new Error("Expected the field `organisationIdentifications` to be an array in the JSON data but got " + data['organisationIdentifications']);
            }
            // validate the optional field `organisationIdentifications` (array)
            for (const item of data['organisationIdentifications']) {
                OrganisationIdentification.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }

        return true;
    }


}



/**
 * @member {module:model/BusinessAddress} businessAddress
 */
EntityDetails.prototype['businessAddress'] = undefined;

/**
 * Matched Entity name.
 * @member {String} businessName
 */
EntityDetails.prototype['businessName'] = undefined;

/**
 * Ids of the merchant in the MMH location database (count contain many).
 * @member {Array.<String>} merchantIds
 */
EntityDetails.prototype['merchantIds'] = undefined;

/**
 * Matched Entity's organisation ID details.
 * @member {Array.<module:model/OrganisationIdentification>} organisationIdentifications
 */
EntityDetails.prototype['organisationIdentifications'] = undefined;

/**
 * Matched phone number of the Entity.
 * @member {String} phoneNumber
 */
EntityDetails.prototype['phoneNumber'] = undefined;






export default EntityDetails;

