/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorList from './ErrorList';

/**
 * The ErrorWrapper model module.
 * @module model/ErrorWrapper
 * @version 1.0.0
 */
class ErrorWrapper {
    /**
     * Constructs a new <code>ErrorWrapper</code>.
     * @alias module:model/ErrorWrapper
     * @param errors {module:model/ErrorList} 
     */
    constructor(errors) { 
        
        ErrorWrapper.initialize(this, errors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, errors) { 
        obj['Errors'] = errors;
    }

    /**
     * Constructs a <code>ErrorWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorWrapper} obj Optional instance to populate.
     * @return {module:model/ErrorWrapper} The populated <code>ErrorWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorWrapper();

            if (data.hasOwnProperty('Errors')) {
                obj['Errors'] = ErrorList.constructFromObject(data['Errors']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ErrorWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ErrorWrapper</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ErrorWrapper.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `Errors`
        if (data['Errors']) { // data not null
          ErrorList.validateJSON(data['Errors']);
        }

        return true;
    }


}

ErrorWrapper.RequiredProperties = ["Errors"];

/**
 * @member {module:model/ErrorList} Errors
 */
ErrorWrapper.prototype['Errors'] = undefined;






export default ErrorWrapper;

