/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewBulkSearchResult model module.
 * @module model/NewBulkSearchResult
 * @version 1.0.0
 */
class NewBulkSearchResult {
    /**
     * Constructs a new <code>NewBulkSearchResult</code>.
     * @alias module:model/NewBulkSearchResult
     * @param bulkSearchId {String} A UUID which uniquely identifies a resource
     */
    constructor(bulkSearchId) { 
        
        NewBulkSearchResult.initialize(this, bulkSearchId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bulkSearchId) { 
        obj['bulkSearchId'] = bulkSearchId;
    }

    /**
     * Constructs a <code>NewBulkSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewBulkSearchResult} obj Optional instance to populate.
     * @return {module:model/NewBulkSearchResult} The populated <code>NewBulkSearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewBulkSearchResult();

            if (data.hasOwnProperty('bulkSearchId')) {
                obj['bulkSearchId'] = ApiClient.convertToType(data['bulkSearchId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewBulkSearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewBulkSearchResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NewBulkSearchResult.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bulkSearchId'] && !(typeof data['bulkSearchId'] === 'string' || data['bulkSearchId'] instanceof String)) {
            throw new Error("Expected the field `bulkSearchId` to be a primitive type in the JSON string but got " + data['bulkSearchId']);
        }

        return true;
    }


}

NewBulkSearchResult.RequiredProperties = ["bulkSearchId"];

/**
 * A UUID which uniquely identifies a resource
 * @member {String} bulkSearchId
 */
NewBulkSearchResult.prototype['bulkSearchId'] = undefined;






export default NewBulkSearchResult;

