/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BpsDetails from './BpsDetails';
import CardProcessingHistory from './CardProcessingHistory';
import EntityDetails from './EntityDetails';
import SearchError from './SearchError';

/**
 * The SearchResult model module.
 * @module model/SearchResult
 * @version 1.0.0
 */
class SearchResult {
    /**
     * Constructs a new <code>SearchResult</code>.
     * Lowest-level details of the search result.
     * @alias module:model/SearchResult
     */
    constructor() { 
        
        SearchResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchResult} obj Optional instance to populate.
     * @return {module:model/SearchResult} The populated <code>SearchResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchResult();

            if (data.hasOwnProperty('bpsDetails')) {
                obj['bpsDetails'] = BpsDetails.constructFromObject(data['bpsDetails']);
            }
            if (data.hasOwnProperty('cardProcessingHistory')) {
                obj['cardProcessingHistory'] = CardProcessingHistory.constructFromObject(data['cardProcessingHistory']);
            }
            if (data.hasOwnProperty('entityDetails')) {
                obj['entityDetails'] = EntityDetails.constructFromObject(data['entityDetails']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [SearchError]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `bpsDetails`
        if (data['bpsDetails']) { // data not null
          BpsDetails.validateJSON(data['bpsDetails']);
        }
        // validate the optional field `cardProcessingHistory`
        if (data['cardProcessingHistory']) { // data not null
          CardProcessingHistory.validateJSON(data['cardProcessingHistory']);
        }
        // validate the optional field `entityDetails`
        if (data['entityDetails']) { // data not null
          EntityDetails.validateJSON(data['entityDetails']);
        }
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                SearchError.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/BpsDetails} bpsDetails
 */
SearchResult.prototype['bpsDetails'] = undefined;

/**
 * @member {module:model/CardProcessingHistory} cardProcessingHistory
 */
SearchResult.prototype['cardProcessingHistory'] = undefined;

/**
 * @member {module:model/EntityDetails} entityDetails
 */
SearchResult.prototype['entityDetails'] = undefined;

/**
 * List of all the errors that were encountered for the search request.
 * @member {Array.<module:model/SearchError>} errors
 */
SearchResult.prototype['errors'] = undefined;






export default SearchResult;

