/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MastercardTrackSearchApi);
  }
}(this, function(expect, MastercardTrackSearchApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MastercardTrackSearchApi.CardProcessingHistory();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardProcessingHistory', function() {
    it('should create an instance of CardProcessingHistory', function() {
      // uncomment below and update the code to test CardProcessingHistory
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be.a(MastercardTrackSearchApi.CardProcessingHistory);
    });

    it('should have the property commercialHistory (base name: "commercialHistory")', function() {
      // uncomment below and update the code to test the property commercialHistory
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property commercialRecency (base name: "commercialRecency")', function() {
      // uncomment below and update the code to test the property commercialRecency
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property inControlHistory (base name: "inControlHistory")', function() {
      // uncomment below and update the code to test the property inControlHistory
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property inControlRecency (base name: "inControlRecency")', function() {
      // uncomment below and update the code to test the property inControlRecency
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property mcc (base name: "mcc")', function() {
      // uncomment below and update the code to test the property mcc
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property mccGroup (base name: "mccGroup")', function() {
      // uncomment below and update the code to test the property mccGroup
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property minorityOwned (base name: "minorityOwned")', function() {
      // uncomment below and update the code to test the property minorityOwned
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property nonProfit (base name: "nonProfit")', function() {
      // uncomment below and update the code to test the property nonProfit
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property purchaseCardLevel (base name: "purchaseCardLevel")', function() {
      // uncomment below and update the code to test the property purchaseCardLevel
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property smallBusiness (base name: "smallBusiness")', function() {
      // uncomment below and update the code to test the property smallBusiness
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property transactionRecency (base name: "transactionRecency")', function() {
      // uncomment below and update the code to test the property transactionRecency
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

    it('should have the property womenOwned (base name: "womenOwned")', function() {
      // uncomment below and update the code to test the property womenOwned
      //var instance = new MastercardTrackSearchApi.CardProcessingHistory();
      //expect(instance).to.be();
    });

  });

}));
