/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MastercardTrackSearchApi);
  }
}(this, function(expect, MastercardTrackSearchApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MastercardTrackSearchApi.SearchResults();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchResults', function() {
    it('should create an instance of SearchResults', function() {
      // uncomment below and update the code to test SearchResults
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be.a(MastercardTrackSearchApi.SearchResults);
    });

    it('should have the property bpsRegistrationId (base name: "bpsRegistrationId")', function() {
      // uncomment below and update the code to test the property bpsRegistrationId
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

    it('should have the property isBpsRegistered (base name: "isBpsRegistered")', function() {
      // uncomment below and update the code to test the property isBpsRegistered
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

    it('should have the property confidence (base name: "confidence")', function() {
      // uncomment below and update the code to test the property confidence
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

    it('should have the property isMatched (base name: "isMatched")', function() {
      // uncomment below and update the code to test the property isMatched
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

    it('should have the property searchRequestId (base name: "searchRequestId")', function() {
      // uncomment below and update the code to test the property searchRequestId
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

    it('should have the property searchResult (base name: "searchResult")', function() {
      // uncomment below and update the code to test the property searchResult
      //var instance = new MastercardTrackSearchApi.SearchResults();
      //expect(instance).to.be();
    });

  });

}));
