/**
 * Mastercard Track Search API
 * All functionality related to the search service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BpsDetails from './model/BpsDetails';
import BulkSearchResult from './model/BulkSearchResult';
import BulkSearchResults from './model/BulkSearchResults';
import BulkSearchStatus from './model/BulkSearchStatus';
import BusinessAddress from './model/BusinessAddress';
import CardProcessingHistory from './model/CardProcessingHistory';
import EntityDetails from './model/EntityDetails';
import Error from './model/Error';
import ErrorList from './model/ErrorList';
import ErrorWrapper from './model/ErrorWrapper';
import NewBulkSearch from './model/NewBulkSearch';
import NewBulkSearchResult from './model/NewBulkSearchResult';
import OrganisationIdentification from './model/OrganisationIdentification';
import RequesterInformation from './model/RequesterInformation';
import RequesterOrganisationIdentification from './model/RequesterOrganisationIdentification';
import RequestingBusinessAddress from './model/RequestingBusinessAddress';
import SearchError from './model/SearchError';
import SearchRequestEntity from './model/SearchRequestEntity';
import SearchResult from './model/SearchResult';
import SearchResults from './model/SearchResults';
import TrackSearchApi from './api/TrackSearchApi';


/**
* All functionality related to the search service.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MastercardTrackSearchApi = require('index'); // See note below*.
* var xxxSvc = new MastercardTrackSearchApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MastercardTrackSearchApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MastercardTrackSearchApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MastercardTrackSearchApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BpsDetails model constructor.
     * @property {module:model/BpsDetails}
     */
    BpsDetails,

    /**
     * The BulkSearchResult model constructor.
     * @property {module:model/BulkSearchResult}
     */
    BulkSearchResult,

    /**
     * The BulkSearchResults model constructor.
     * @property {module:model/BulkSearchResults}
     */
    BulkSearchResults,

    /**
     * The BulkSearchStatus model constructor.
     * @property {module:model/BulkSearchStatus}
     */
    BulkSearchStatus,

    /**
     * The BusinessAddress model constructor.
     * @property {module:model/BusinessAddress}
     */
    BusinessAddress,

    /**
     * The CardProcessingHistory model constructor.
     * @property {module:model/CardProcessingHistory}
     */
    CardProcessingHistory,

    /**
     * The EntityDetails model constructor.
     * @property {module:model/EntityDetails}
     */
    EntityDetails,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorList model constructor.
     * @property {module:model/ErrorList}
     */
    ErrorList,

    /**
     * The ErrorWrapper model constructor.
     * @property {module:model/ErrorWrapper}
     */
    ErrorWrapper,

    /**
     * The NewBulkSearch model constructor.
     * @property {module:model/NewBulkSearch}
     */
    NewBulkSearch,

    /**
     * The NewBulkSearchResult model constructor.
     * @property {module:model/NewBulkSearchResult}
     */
    NewBulkSearchResult,

    /**
     * The OrganisationIdentification model constructor.
     * @property {module:model/OrganisationIdentification}
     */
    OrganisationIdentification,

    /**
     * The RequesterInformation model constructor.
     * @property {module:model/RequesterInformation}
     */
    RequesterInformation,

    /**
     * The RequesterOrganisationIdentification model constructor.
     * @property {module:model/RequesterOrganisationIdentification}
     */
    RequesterOrganisationIdentification,

    /**
     * The RequestingBusinessAddress model constructor.
     * @property {module:model/RequestingBusinessAddress}
     */
    RequestingBusinessAddress,

    /**
     * The SearchError model constructor.
     * @property {module:model/SearchError}
     */
    SearchError,

    /**
     * The SearchRequestEntity model constructor.
     * @property {module:model/SearchRequestEntity}
     */
    SearchRequestEntity,

    /**
     * The SearchResult model constructor.
     * @property {module:model/SearchResult}
     */
    SearchResult,

    /**
     * The SearchResults model constructor.
     * @property {module:model/SearchResults}
     */
    SearchResults,

    /**
    * The TrackSearchApi service constructor.
    * @property {module:api/TrackSearchApi}
    */
    TrackSearchApi
};
